seat = []
for i in range(50):
    i = 0
    seat.append(i)

seat2 = "".join(str(i) for i in seat)

a = open("PtLF001.txt", "w")
b = open("PtLF002.txt", "w")
c = open("PtLF003.txt", "w")

d = open("PtLF004.txt", "w")
e = open("PtLF005.txt", "w")
f = open("PtLF006.txt", "w")
g = open("PtLF007.txt", "w")
h = open("PtLF008.txt", "w")
i = open("LtPF001.txt", "w")
j = open("LtPF002.txt", "w")
k = open("LtPF003.txt", "w")
l = open("LtPF004.txt", "w")
m = open("LtPF005.txt", "w")
n = open("LtPF006.txt", "w")
o = open("LtPF007.txt", "w")
p = open("LtPF008.txt", "w")

a.write(seat2)
b.write(seat2)
c.write(seat2)
d.write(seat2)
e.write(seat2)
f.write(seat2)
g.write(seat2)
h.write(seat2)
i.write(seat2)
j.write(seat2)
k.write(seat2)
l.write(seat2)
m.write(seat2)
n.write(seat2)
o.write(seat2)
p.write(seat2)
 
a.close()
b.close()
c.close()
d.close()
e.close()
f.close()
g.close()
h.close()
i.close()
j.close()
k.close()
l.close()
m.close()
n.close()
o.close()
p.close()

 
